security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        shibboleth:
            id: App\Security\Provider\ShibbolethUserProvider
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        shibboleth:
            context: main
            pattern: ^/shibboleth-login
            anonymous: lazy
            provider: shibboleth
            guard:
                authenticators:
                    - unicesil.shibboleth_authenticator
            logout: ~
        basic:
            context: main
            pattern: ^/
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\FormAuthenticator
            logout:
                path: app.logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
