tetranz_select2_entity:
  #minimum_input_length: 2
  #page_limit: 8
  #allow_clear: true
  #delay: 500
  language: '%locale%'
  #theme: 'default'
  #cache: false
  #cache_timeout: 0
  #scroll: true
  #object_manager: 'manager_alias'
  #render_html: true