twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        app_name: '%app_name%'
        layout_default_class: '%layout_default_class%'
        layout_sidebar_class: '%layout_sidebar_class%'
        container_default: '%container_default%'
