vich_uploader:
    db_driver: orm

    mappings:
        reports:
            uri_prefix: '%report_folder_uri%'
            upload_destination: '%kernel.project_dir%/%report_folder_uri%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
