vich_uploader:
    db_driver: orm

    mappings:
        reports:
            uri_prefix: '%report_folder_uri%'
            upload_destination: '%file_folder%/%report_folder_uri%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
