version: '3.7'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_preferences
        restart: always
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
    php:
        container_name: php
        build: php
        ports:
            - "9000:8000"
        volumes:
            - .:/app
            - /app/vendor # ignore vendor folder
volumes:
    persistent:


