version: '3.7'

services:
    database:
        container_name: ${PROJECT_NAME:-aap}_database
        image: 'mariadb:10.3.34'
        environment:
            MARIADB_NAME: ${DATABASE_NAME:-aap}
            MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-password}
        ports:
            - ${DATABASE_PORT:-3380}:3306
        volumes:
            - db-data:/var/lib/mysql:rw
        networks:
            - default

    phpmyadmin:
        container_name: ${PROJECT_NAME:-aap}_phpmyadmin
        image: phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT:-9081}:80
        environment:
            PMA_HOST: database
        depends_on:
            - database
        networks:
            - default

    php:
        container_name: ${PROJECT_NAME:-aap}_php
        tty: true
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        env_file:
            - .env.local
        environment:
            DATABASE_URL: mysql://root:${DATABASE_ROOT_PASSWORD:-password}@database/${DATABASE_NAME:-aap}?serverVersion=mariadb-${DATABASE_VERSION:-10.3.34}
        ports:
            - ${PHP_PORT:-9080}:8000
        volumes:
            - .:/web/app:cached
            - /web/app/node_modules
            - /web/app/var/cache
            #- /web/app/vendor
        depends_on:
            - database
        networks:
            - default

networks:
    default:

volumes:
    db-data:


