controllers:
    resource: ../../src/Controller/Front
    type: annotation
    name_prefix: app.

admin_controllers:
    resource: ../../src/Controller/Admin
    type: annotation
    name_prefix: app.admin.
    prefix: /admin

#admin_controllers:
#    resource: ../../src/Controller/Admin
#    type: annotation
#    prefix: /admin
#    name_prefix: app.admin.

kernel:
    resource: ../../src/Kernel.php
    type: annotation
